version: "3.7"

services:
  nginx:
    command: ["nginx", "-c", "/root/project/docker/nginx.conf"]
    image: luissaybe/seoullatte
    ports:
      - 80:80
    volumes:
      - ".:/root/project"
  install:
    image: luissaybe/seoullatte
    command: yarn
    volumes:
      - ".:/root/project"
  watch:
    depends_on:
      - install
    image: luissaybe/seoullatte
    command: yarn watch
    volumes:
      - ".:/root/project"
