version: "3.7"

services:
  nginx:
    command: ["nginx", "-c", "/root/project/docker/nginx.conf"]
    image: luissaybe/seoullatte
    ports:
      - 80:80
    volumes:
      - ".:/root/project"
  watch:
    command: ["npm", "run", "watch"]
    image: luissaybe/seoullatte
    volumes:
      - ".:/root/project"
  install:
    command: ["npm", "install"]
    image: luissaybe/seoullatte
    volumes:
      - ".:/root/project"
