export type LocationsContextType = Array<{ pathname: string }>;

export enum TopicRoute {
  hangul = "/hangul",
  noun = "/noun",
  predicate = "/predicate",
  counting = "/counting",
  copular = "/copular",
  desire = "/desire",
  equivalence = "/equivalence",
  existenceAndPosession = "/existence-and-posession",
  boundNoun = "/bound-noun",
  prenoun = "/prenoun",
  suffixes = "/suffixes",
  irregularPredicate = "/irregular-predicate",
  ending = "/ending",
  formalAndInformalSpeech = "/formal-and-informal-speech",
  deferentialSpeech = "/deferential-speech",
  politeSpeech = "/polite-speech",
  plainSpeech = "/plain-speech",
  intimateSpeech = "/intimate-speech",
  familiarSpeech = "/familiar-speech",
  syllable = "/syllable",
  speechLevel = "/speech-level",
  pastTense = "/past-tense",
  predicateAsModifiers = "/predicate-as-modifiers",
  subjectAndTopicParticle = "/subject-and-topic",
}
